<?php

return [
    'disk' => env('UPLOADS_DISK', 'local'),
    'signed_download_ttl_minutes' => (int) env('UPLOADS_SIGNED_DOWNLOAD_TTL_MINUTES', 10),
    'max_upload_kb' => (int) env('UPLOADS_MAX_UPLOAD_KB', 20 * 1024),
    'ffprobe_binary' => env('FFPROBE_BINARY', 'ffprobe'),
    'clamav' => [
        'enabled' => (bool) env('CLAMAV_ENABLED', false),
        'binary' => env('CLAMAV_BINARY', 'clamscan'),
    ],
    'allowed_mime_types' => [
        'image/jpeg',
        'image/png',
        'image/webp',
        'image/gif',
        'video/mp4',
        'video/webm',
        'audio/mpeg',
        'audio/mp4',
        'audio/ogg',
        'audio/webm',
        'audio/wav',
        'application/pdf',
        'application/json',
        'text/plain',
        'text/csv',
        'text/markdown',
        'application/vnd.ms-excel',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-powerpoint',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'application/zip',
        'application/x-zip-compressed',
        'application/x-rar-compressed',
        'application/vnd.rar',
        'application/x-7z-compressed',
        'application/octet-stream',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/msword',
    ],
    'allow_unlisted_file_types' => (bool) env('UPLOADS_ALLOW_UNLISTED_FILE_TYPES', true),
];
